name: Child

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
  workflow_dispatch:
jobs:

  check_release:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: |
          echo ${{ github.event.workflow_run }}
          exit 1;

  child_event: 
    runs-on: ubuntu-latest
    needs: check_release
    steps:
      - run: echo "OK"
