name: Child

on:
  workflow_run:
    workflows: ["Deploy"]
    types: [completed]
  workflow_dispatch:
jobs:

  check_release:
    runs-on: ubuntu-latest

    steps:
      - run: |
          if [${{ github.event.workflow_run.conclusion }} == 'failure']; then exit 1; fi

  child_event: 
    runs-on: ubuntu-latest
    needs: check_release
    steps:
      - run: echo "OK"
