name: Deploy

on:

  workflow_dispatch:
    inputs:
      test_input:
        description: "un champs lambda"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          echo "Debut du script"
          echo $GITHUB_REF
