name: Deploy

on:

  workflow_dispatch:
    inputs:
      test_input:
        description: "un champs lambda"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          cd ${{ github.workspace }}
          pwd
          ls -al
          exit 1;
          echo "Debut du script"
          echo $GITHUB_REF
