name: Reusable check mongo

on:
  workflow_call:
    inputs:
      env:
        required: true
        description: 'Environment to check (e.g. sit, uat1, prep, prod)'
        type: string
      business_unit:
        required: true
        description: 'The business unit to check database as it is provided in vault (e.g. lmfr, lmit, lmes ...).'
        type: string

jobs:
  check_mongo_database:
    runs-on: [ self-hosted, linux, standard ]
    permissions:
      contents: read
      id-token: write

    steps:
      - name:




